openapi: 3.0.0
info:
  title: Nginx Proxy Manager API
  version: 2.x.x
servers:
- url: https://pmp.cwrd.com.br/api
paths:
  /:
    get:
      summary: Returns the API health status
      operationId: health
      x-swagger-router-controller: Default
  /schema:
    get:
      summary: Returns this swagger API schema
      operationId: schema
      x-swagger-router-controller: Default
  /tokens:
    get:
      tags:
      - Tokens
      summary: Refresh your access token
      operationId: refreshToken
      security:
      - BearerAuth:
        - tokens
      x-swagger-router-controller: Tokens
    post:
      tags:
      - Tokens
      summary: Request a new access token from credentials
      operationId: requestToken
      x-swagger-router-controller: Tokens
  /settings:
    get:
      tags:
      - Settings
      summary: Get all settings
      operationId: getSettings
      security:
      - BearerAuth:
        - settings
      x-swagger-router-controller: Settings
  /settings/{settingID}:
    get:
      tags:
      - Settings
      summary: Get a setting
      operationId: getSetting
      security:
      - BearerAuth:
        - settings
      x-swagger-router-controller: Settings
    put:
      tags:
      - Settings
      summary: Update a setting
      operationId: updateSetting
      security:
      - BearerAuth:
        - settings
      x-swagger-router-controller: Settings
  /users:
    get:
      tags:
      - Users
      summary: Get all users
      operationId: getUsers
      security:
      - BearerAuth:
        - users
      x-swagger-router-controller: Users
    post:
      tags:
      - Users
      summary: Create a User
      operationId: createUser
      security:
      - BearerAuth:
        - users
      x-swagger-router-controller: Users
  /users/{userID}:
    get:
      tags:
      - Users
      summary: Get a user
      operationId: getUser
      security:
      - BearerAuth:
        - users
      x-swagger-router-controller: Users
    put:
      tags:
      - Users
      summary: Update a User
      operationId: updateUser
      security:
      - BearerAuth:
        - users
      x-swagger-router-controller: Users
    delete:
      tags:
      - Users
      summary: Delete a User
      operationId: deleteUser
      security:
      - BearerAuth:
        - users
      x-swagger-router-controller: Users
  /users/{userID}/auth:
    put:
      tags:
      - Users
      summary: Update a User's Authentication
      operationId: updateUserAuth
      security:
      - BearerAuth:
        - users
      x-swagger-router-controller: Users
  /users/{userID}/permissions:
    put:
      tags:
      - Users
      summary: Update a User's Permissions
      operationId: updateUserPermissions
      security:
      - BearerAuth:
        - users
      x-swagger-router-controller: Users
  /users/{userID}/login:
    put:
      tags:
      - Users
      summary: Login as this user
      operationId: loginAsUser
      security:
      - BearerAuth:
        - users
      x-swagger-router-controller: Users
  /reports/hosts:
    get:
      tags:
      - Reports
      summary: Report on Host Statistics
      operationId: reportsHosts
      security:
      - BearerAuth:
        - reports
      x-swagger-router-controller: Reports
  /audit-log:
    get:
      tags:
      - Audit Log
      summary: Get Audit Log
      operationId: getAuditLog
      security:
      - BearerAuth:
        - audit-log
      x-swagger-router-controller: AuditLog
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
